defconfig: Partial revert of previous commit
DRM/SDE drivers fail to link due to undefined reference to functions
that CONFIG_BACKLIGHT_CLASS_DEVICE=y provides.

Signed-off-by: Artem Labazov <123321artyom@gmail.com>